//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnitterNotebook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnitterNotebook.Properties.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add movie&apos;s url.
        /// </summary>
        public static string AddMovieUrl {
            get {
                return ResourceManager.GetString("AddMovieUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project&apos;s photo.
        /// </summary>
        public static string AddProjectPhoto {
            get {
                return ResourceManager.GetString("AddProjectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sample.
        /// </summary>
        public static string AddSample {
            get {
                return ResourceManager.GetString("AddSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s theme.
        /// </summary>
        public static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s theme changed successfully.
        /// </summary>
        public static string ApplicationThemeChangedSuccessfully {
            get {
                return ResourceManager.GetString("ApplicationThemeChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will shut down.
        /// </summary>
        public static string ApplicationWillShutDown {
            get {
                return ResourceManager.GetString("ApplicationWillShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose .pdf file with pattern.
        /// </summary>
        public static string ChoosePdfFileWithPattern {
            get {
                return ResourceManager.GetString("ChoosePdfFileWithPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose photo.
        /// </summary>
        public static string ChoosePhoto {
            get {
                return ResourceManager.GetString("ChoosePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete link.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .pdf file with pattern.
        /// </summary>
        public static string DeletePdfFileWithPattern {
            get {
                return ResourceManager.GetString("DeletePdfFileWithPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete photo.
        /// </summary>
        public static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sample.
        /// </summary>
        public static string DeleteSample {
            get {
                return ResourceManager.GetString("DeleteSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can&apos;t have more than.
        /// </summary>
        public static string DescriptionMaxChars {
            get {
                return ResourceManager.GetString("DescriptionMaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit planned project.
        /// </summary>
        public static string EditPlannedProject {
            get {
                return ResourceManager.GetString("EditPlannedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project in progress.
        /// </summary>
        public static string EditProjectInProgress {
            get {
                return ResourceManager.GetString("EditProjectInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail can&apos;t be empty.
        /// </summary>
        public static string EmailCantBeEmpty {
            get {
                return ResourceManager.GetString("EmailCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email changed successfully.
        /// </summary>
        public static string EmailChangedSuccessfully {
            get {
                return ResourceManager.GetString("EmailChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is already taken.
        /// </summary>
        public static string EmailIsAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding movie&apos;s url.
        /// </summary>
        public static string ErrorWhileAddingMovieUrl {
            get {
                return ResourceManager.GetString("ErrorWhileAddingMovieUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding new sample.
        /// </summary>
        public static string ErrorWhileAddingNewSample {
            get {
                return ResourceManager.GetString("ErrorWhileAddingNewSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding project&apos;s photo.
        /// </summary>
        public static string ErrorWhileAddingProjectPhoto {
            get {
                return ResourceManager.GetString("ErrorWhileAddingProjectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing application&apos;s theme.
        /// </summary>
        public static string ErrorWhileChangingApplicationTheme {
            get {
                return ResourceManager.GetString("ErrorWhileChangingApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing e-mail.
        /// </summary>
        public static string ErrorWhileChangingEmail {
            get {
                return ResourceManager.GetString("ErrorWhileChangingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing nickname.
        /// </summary>
        public static string ErrorWhileChangingNickname {
            get {
                return ResourceManager.GetString("ErrorWhileChangingNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while changing password.
        /// </summary>
        public static string ErrorWhileChangingPassword {
            get {
                return ResourceManager.GetString("ErrorWhileChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting finished project.
        /// </summary>
        public static string ErrorWhileDeletingFinishedProject {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingFinishedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting finished project&apos;s photo.
        /// </summary>
        public static string ErrorWhileDeletingFinishedProjectPhoto {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingFinishedProjectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting movie&apos;s url.
        /// </summary>
        public static string ErrorWhileDeletingMovieUrl {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingMovieUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting planned project.
        /// </summary>
        public static string ErrorWhileDeletingPlannedProject {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingPlannedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting project in progress.
        /// </summary>
        public static string ErrorWhileDeletingProjectInProgress {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingProjectInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting project in progress photo.
        /// </summary>
        public static string ErrorWhileDeletingProjectInProgressPhoto {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingProjectInProgressPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting sample.
        /// </summary>
        public static string ErrorWhileDeletingSample {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while editing project.
        /// </summary>
        public static string ErrorWhileEditingProject {
            get {
                return ResourceManager.GetString("ErrorWhileEditingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while finishing project in progress.
        /// </summary>
        public static string ErrorWhileFinishingProjectInProgress {
            get {
                return ResourceManager.GetString("ErrorWhileFinishingProjectInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while moving finished project to projects in progress.
        /// </summary>
        public static string ErrorWhileMovingFinishedProjectToProjectsInProgress {
            get {
                return ResourceManager.GetString("ErrorWhileMovingFinishedProjectToProjectsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while moving project in progress to planned projects.
        /// </summary>
        public static string ErrorWhileMovingProjectInProgressToPlannedProjects {
            get {
                return ResourceManager.GetString("ErrorWhileMovingProjectInProgressToPlannedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening movie in web browser.
        /// </summary>
        public static string ErrorWhileOpeningMovieInWebBrowser {
            get {
                return ResourceManager.GetString("ErrorWhileOpeningMovieInWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while planning new project.
        /// </summary>
        public static string ErrorWhilePlanningNewProject {
            get {
                return ResourceManager.GetString("ErrorWhilePlanningNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while resetting password.
        /// </summary>
        public static string ErrorWhileResettingPassword {
            get {
                return ResourceManager.GetString("ErrorWhileResettingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while signing up.
        /// </summary>
        public static string ErrorWhileSigningUp {
            get {
                return ResourceManager.GetString("ErrorWhileSigningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while signing in.
        /// </summary>
        public static string ErrorWhileSigninIn {
            get {
                return ResourceManager.GetString("ErrorWhileSigninIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while starting planned project.
        /// </summary>
        public static string ErrorWhileStartingPlannedProject {
            get {
                return ResourceManager.GetString("ErrorWhileStartingPlannedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by needle&apos;s size.
        /// </summary>
        public static string FilterByNeedleSize {
            get {
                return ResourceManager.GetString("FilterByNeedleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by project&apos;s name.
        /// </summary>
        public static string FilterByProjectName {
            get {
                return ResourceManager.GetString("FilterByProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished project.
        /// </summary>
        public static string FinishedProject {
            get {
                return ResourceManager.GetString("FinishedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished projects.
        /// </summary>
        public static string FinishedProjects {
            get {
                return ResourceManager.GetString("FinishedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish project.
        /// </summary>
        public static string FinishProject {
            get {
                return ResourceManager.GetString("FinishProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail&apos;s format.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login credentials.
        /// </summary>
        public static string InvalidLoginCredentials {
            get {
                return ResourceManager.GetString("InvalidLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid project&apos;s status.
        /// </summary>
        public static string InvalidProjectStatus {
            get {
                return ResourceManager.GetString("InvalidProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid size unit.
        /// </summary>
        public static string InvalidSizeUnit {
            get {
                return ResourceManager.GetString("InvalidSizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link can&apos;t be empty.
        /// </summary>
        public static string LinkCantBeEmpty {
            get {
                return ResourceManager.GetString("LinkCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops quantity.
        /// </summary>
        public static string LoopsQuantity {
            get {
                return ResourceManager.GetString("LoopsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops quantity must be between.
        /// </summary>
        public static string LoopsQuantityMustBeBetween {
            get {
                return ResourceManager.GetString("LoopsQuantityMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops x rows.
        /// </summary>
        public static string LoopsXRows {
            get {
                return ResourceManager.GetString("LoopsXRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to planned projects.
        /// </summary>
        public static string MoveToPlannedProjects {
            get {
                return ResourceManager.GetString("MoveToPlannedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to projects in progress.
        /// </summary>
        public static string MoveToProjectsInProgress {
            get {
                return ResourceManager.GetString("MoveToProjectsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle collection can&apos;t be empty.
        /// </summary>
        public static string NeedleCollectionCantBeEmpty {
            get {
                return ResourceManager.GetString("NeedleCollectionCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needles.
        /// </summary>
        public static string Needles {
            get {
                return ResourceManager.GetString("Needles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle&apos;s size.
        /// </summary>
        public static string NeedleSize {
            get {
                return ResourceManager.GetString("NeedleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle&apos;s size must be between.
        /// </summary>
        public static string NeedleSizeMustBeBetween {
            get {
                return ResourceManager.GetString("NeedleSizeMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New e-mail.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New movie&apos;s url added.
        /// </summary>
        public static string NewMovieUrlAdded {
            get {
                return ResourceManager.GetString("NewMovieUrlAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New nickname.
        /// </summary>
        public static string NewNickname {
            get {
                return ResourceManager.GetString("NewNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project planned.
        /// </summary>
        public static string NewProjectPlanned {
            get {
                return ResourceManager.GetString("NewProjectPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sample added.
        /// </summary>
        public static string NewSampleAdded {
            get {
                return ResourceManager.GetString("NewSampleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New theme.
        /// </summary>
        public static string NewTheme {
            get {
                return ResourceManager.GetString("NewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice to see you.
        /// </summary>
        public static string NiceToSeeYou {
            get {
                return ResourceManager.GetString("NiceToSeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname can consist of letters, spaces and numbers.
        /// </summary>
        public static string NicknameCanConsistOfLettersSpacesAndNumbers {
            get {
                return ResourceManager.GetString("NicknameCanConsistOfLettersSpacesAndNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname can&apos;t be empty.
        /// </summary>
        public static string NicknameCantBeEmpty {
            get {
                return ResourceManager.GetString("NicknameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname changed successfully.
        /// </summary>
        public static string NicknameChangedSuccessfully {
            get {
                return ResourceManager.GetString("NicknameChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname is already taken.
        /// </summary>
        public static string NicknameIsAlreadyTaken {
            get {
                return ResourceManager.GetString("NicknameIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname can&apos;t have more than.
        /// </summary>
        public static string NicknameMaxChars {
            get {
                return ResourceManager.GetString("NicknameMaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet specified.
        /// </summary>
        public static string NotYetSpecified {
            get {
                return ResourceManager.GetString("NotYetSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty.
        /// </summary>
        public static string PasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&apos;s length must be between.
        /// </summary>
        public static string PasswordLengthMustBeBetween {
            get {
                return ResourceManager.GetString("PasswordLengthMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one lower letter.
        /// </summary>
        public static string PasswordMustHaveAtLeastOneLowerLetter {
            get {
                return ResourceManager.GetString("PasswordMustHaveAtLeastOneLowerLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one number.
        /// </summary>
        public static string PasswordMustHaveAtLeastOneNumber {
            get {
                return ResourceManager.GetString("PasswordMustHaveAtLeastOneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least one upper letter.
        /// </summary>
        public static string PasswordMustHaveAtLeastOneUpperLetter {
            get {
                return ResourceManager.GetString("PasswordMustHaveAtLeastOneUpperLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not identical.
        /// </summary>
        public static string PasswordsAreNotIdentical {
            get {
                return ResourceManager.GetString("PasswordsAreNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf with pattern.
        /// </summary>
        public static string PdfWithPattern {
            get {
                return ResourceManager.GetString("PdfWithPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo must have .jpg, .jpeg, .png extension.
        /// </summary>
        public static string PhotoValidExtension {
            get {
                return ResourceManager.GetString("PhotoValidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo must have .jpg, .jpeg, .png extension or be empty.
        /// </summary>
        public static string PhotoValidExtensionOrEmpty {
            get {
                return ResourceManager.GetString("PhotoValidExtensionOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated names, e.g.: w1 , w2 , w3.
        /// </summary>
        public static string Placeholder_CommaSeparatedNames {
            get {
                return ResourceManager.GetString("Placeholder_CommaSeparatedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Placeholder_Nickname {
            get {
                return ResourceManager.GetString("Placeholder_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset token.
        /// </summary>
        public static string Placeholder_PasswordResetToken {
            get {
                return ResourceManager.GetString("Placeholder_PasswordResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string Placeholder_RepeatNewPassword {
            get {
                return ResourceManager.GetString("Placeholder_RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type description.
        /// </summary>
        public static string Placeholder_TypeDescription {
            get {
                return ResourceManager.GetString("Placeholder_TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type link.
        /// </summary>
        public static string Placeholder_TypeLink {
            get {
                return ResourceManager.GetString("Placeholder_TypeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type loops quantity.
        /// </summary>
        public static string Placeholder_TypeLoopsQuantity {
            get {
                return ResourceManager.GetString("Placeholder_TypeLoopsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type needle&apos;s size.
        /// </summary>
        public static string Placeholder_TypeNeedleSize {
            get {
                return ResourceManager.GetString("Placeholder_TypeNeedleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new email.
        /// </summary>
        public static string Placeholder_TypeNewEmail {
            get {
                return ResourceManager.GetString("Placeholder_TypeNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new nickname.
        /// </summary>
        public static string Placeholder_TypeNewNickname {
            get {
                return ResourceManager.GetString("Placeholder_TypeNewNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new password.
        /// </summary>
        public static string Placeholder_TypeNewPassword {
            get {
                return ResourceManager.GetString("Placeholder_TypeNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type project&apos;s name.
        /// </summary>
        public static string Placeholder_TypeProjectName {
            get {
                return ResourceManager.GetString("Placeholder_TypeProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type rows quantity.
        /// </summary>
        public static string Placeholder_TypeRowsQuantity {
            get {
                return ResourceManager.GetString("Placeholder_TypeRowsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type title.
        /// </summary>
        public static string Placeholder_TypeTitle {
            get {
                return ResourceManager.GetString("Placeholder_TypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type yarn&apos;s name.
        /// </summary>
        public static string Placeholder_TypeYarnName {
            get {
                return ResourceManager.GetString("Placeholder_TypeYarnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned project.
        /// </summary>
        public static string PlannedProject {
            get {
                return ResourceManager.GetString("PlannedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned projects.
        /// </summary>
        public static string PlannedProjects {
            get {
                return ResourceManager.GetString("PlannedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan out project.
        /// </summary>
        public static string PlanOutProject {
            get {
                return ResourceManager.GetString("PlanOutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play movie.
        /// </summary>
        public static string PlayMovie {
            get {
                return ResourceManager.GetString("PlayMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project edited successfully.
        /// </summary>
        public static string ProjectEditedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectEditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project in progress.
        /// </summary>
        public static string ProjectInProgress {
            get {
                return ResourceManager.GetString("ProjectInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project&apos;s name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project&apos;s name can&apos;t be empty.
        /// </summary>
        public static string ProjectNameCantBeEmpty {
            get {
                return ResourceManager.GetString("ProjectNameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project&apos;s name can&apos;t have more than.
        /// </summary>
        public static string ProjectNameMaxChars {
            get {
                return ResourceManager.GetString("ProjectNameMaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects in progress.
        /// </summary>
        public static string ProjectsInProgress {
            get {
                return ResourceManager.GetString("ProjectsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project&apos;s start date must be today or later or empty.
        /// </summary>
        public static string ProjectStartDateValidOrEmpty {
            get {
                return ResourceManager.GetString("ProjectStartDateValidOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows quantity.
        /// </summary>
        public static string RowsQuantity {
            get {
                return ResourceManager.GetString("RowsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows quantity must be between.
        /// </summary>
        public static string RowsQuantityMustBeBetween {
            get {
                return ResourceManager.GetString("RowsQuantityMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pattern.
        /// </summary>
        public static string ShowPattern {
            get {
                return ResourceManager.GetString("ShowPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start project.
        /// </summary>
        public static string StartProject {
            get {
                return ResourceManager.GetString("StartProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme not found.
        /// </summary>
        public static string ThemeNotFound {
            get {
                return ResourceManager.GetString("ThemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can&apos;t be empty.
        /// </summary>
        public static string TitleCantBeEmpty {
            get {
                return ResourceManager.GetString("TitleCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can&apos;t have more than 100 characters.
        /// </summary>
        public static string TitleMax100Chars {
            get {
                return ResourceManager.GetString("TitleMax100Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is invalid or expired.
        /// </summary>
        public static string TokenInvalidOrExpired {
            get {
                return ResourceManager.GetString("TokenInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type e-mail.
        /// </summary>
        public static string TypeEmail {
            get {
                return ResourceManager.GetString("TypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new login credentials.
        /// </summary>
        public static string TypeNewLoginCredentials {
            get {
                return ResourceManager.GetString("TypeNewLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s account.
        /// </summary>
        public static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be empty.
        /// </summary>
        public static string ValueCantBeEmpty {
            get {
                return ResourceManager.GetString("ValueCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Knitter Notebook.
        /// </summary>
        public static string WelcomeToKnitterNotebook {
            get {
                return ResourceManager.GetString("WelcomeToKnitterNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you token necessary to reset your password.
        /// </summary>
        public static string WeWillSendPasswordResetToken {
            get {
                return ResourceManager.GetString("WeWillSendPasswordResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarn collection can&apos;t be empty.
        /// </summary>
        public static string YarnCollectionCantBeEmpty {
            get {
                return ResourceManager.GetString("YarnCollectionCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarn&apos;s name.
        /// </summary>
        public static string YarnName {
            get {
                return ResourceManager.GetString("YarnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarn&apos;s name can&apos;t be empty.
        /// </summary>
        public static string YarnNameCantBeEmpty {
            get {
                return ResourceManager.GetString("YarnNameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarn&apos;s name can&apos;t have more than 100 characters.
        /// </summary>
        public static string YarnNameMax100Chars {
            get {
                return ResourceManager.GetString("YarnNameMax100Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarns.
        /// </summary>
        public static string Yarns {
            get {
                return ResourceManager.GetString("Yarns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YarnsNames.
        /// </summary>
        public static string YarnsNames {
            get {
                return ResourceManager.GetString("YarnsNames", resourceCulture);
            }
        }
    }
}
