//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnitterNotebook.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnitterNotebook.Translations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add movie&apos;s url.
        /// </summary>
        public static string AddMovieUrl {
            get {
                return ResourceManager.GetString("AddMovieUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sample.
        /// </summary>
        public static string AddSample {
            get {
                return ResourceManager.GetString("AddSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s theme.
        /// </summary>
        public static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete link.
        /// </summary>
        public static string DeleteLink {
            get {
                return ResourceManager.GetString("DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete photo.
        /// </summary>
        public static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project.
        /// </summary>
        public static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sample.
        /// </summary>
        public static string DeleteSample {
            get {
                return ResourceManager.GetString("DeleteSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by needle&apos;s size.
        /// </summary>
        public static string FilterByNeedleSize {
            get {
                return ResourceManager.GetString("FilterByNeedleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by project&apos;s name.
        /// </summary>
        public static string FilterByProjectName {
            get {
                return ResourceManager.GetString("FilterByProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished project.
        /// </summary>
        public static string FinishedProject {
            get {
                return ResourceManager.GetString("FinishedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished projects.
        /// </summary>
        public static string FinishedProjects {
            get {
                return ResourceManager.GetString("FinishedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish project.
        /// </summary>
        public static string FinishProject {
            get {
                return ResourceManager.GetString("FinishProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Knitter Notebook.
        /// </summary>
        public static string LogInHeader {
            get {
                return ResourceManager.GetString("LogInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loops x rows.
        /// </summary>
        public static string LoopsXRows {
            get {
                return ResourceManager.GetString("LoopsXRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to planned projects.
        /// </summary>
        public static string MoveToPlannedProjects {
            get {
                return ResourceManager.GetString("MoveToPlannedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to projects in progress.
        /// </summary>
        public static string MoveToProjectsInProgress {
            get {
                return ResourceManager.GetString("MoveToProjectsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needles.
        /// </summary>
        public static string Needles {
            get {
                return ResourceManager.GetString("Needles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle&apos;s size.
        /// </summary>
        public static string NeedleSize {
            get {
                return ResourceManager.GetString("NeedleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New e-mail.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New nickname.
        /// </summary>
        public static string NewNickname {
            get {
                return ResourceManager.GetString("NewNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New theme.
        /// </summary>
        public static string NewTheme {
            get {
                return ResourceManager.GetString("NewTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet specified.
        /// </summary>
        public static string NotYetSpecified {
            get {
                return ResourceManager.GetString("NotYetSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Placeholder_Email {
            get {
                return ResourceManager.GetString("Placeholder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Placeholder_Password {
            get {
                return ResourceManager.GetString("Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string Placeholder_RepeatNewPassword {
            get {
                return ResourceManager.GetString("Placeholder_RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type description.
        /// </summary>
        public static string Placeholder_TypeDescription {
            get {
                return ResourceManager.GetString("Placeholder_TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type link.
        /// </summary>
        public static string Placeholder_TypeLink {
            get {
                return ResourceManager.GetString("Placeholder_TypeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new email.
        /// </summary>
        public static string Placeholder_TypeNewEmail {
            get {
                return ResourceManager.GetString("Placeholder_TypeNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new nickname.
        /// </summary>
        public static string Placeholder_TypeNewNickname {
            get {
                return ResourceManager.GetString("Placeholder_TypeNewNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new password.
        /// </summary>
        public static string Placeholder_TypeNewPassword {
            get {
                return ResourceManager.GetString("Placeholder_TypeNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type title.
        /// </summary>
        public static string Placeholder_TypeTitle {
            get {
                return ResourceManager.GetString("Placeholder_TypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned project.
        /// </summary>
        public static string PlannedProject {
            get {
                return ResourceManager.GetString("PlannedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned projects.
        /// </summary>
        public static string PlannedProjects {
            get {
                return ResourceManager.GetString("PlannedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan out project.
        /// </summary>
        public static string PlanOutProject {
            get {
                return ResourceManager.GetString("PlanOutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play movie.
        /// </summary>
        public static string PlayMovie {
            get {
                return ResourceManager.GetString("PlayMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project in progress.
        /// </summary>
        public static string ProjectInProgress {
            get {
                return ResourceManager.GetString("ProjectInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects in progress.
        /// </summary>
        public static string ProjectsInProgress {
            get {
                return ResourceManager.GetString("ProjectsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pattern.
        /// </summary>
        public static string ShowPattern {
            get {
                return ResourceManager.GetString("ShowPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start project.
        /// </summary>
        public static string StartProject {
            get {
                return ResourceManager.GetString("StartProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s account.
        /// </summary>
        public static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarn&apos;s name.
        /// </summary>
        public static string YarnName {
            get {
                return ResourceManager.GetString("YarnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarns.
        /// </summary>
        public static string Yarns {
            get {
                return ResourceManager.GetString("Yarns", resourceCulture);
            }
        }
    }
}
